### ISSUE TITLE
Delete rows not sync

### ISSUE THREAD

**Issue by mohamedmostafa20** [WCOMAB/SqlBulkSync#1]
Hello dear,
I'm have problem, when delete rows from source database and run SqlBulkSync the rows has been deleted from source database not sync to target database but when delete file current version in folder "SyncState" and run SqlBulkSync, rows has been deleted sync.

I have need your response is necessary
Thanks,

**Comment by devlead** [comment]
Hi @mohamedmostafa20,

A version that supports delete is now in the works via PR #2, if you want to test it you can download it from the build server via
https://ci.appveyor.com/project/WCOMAB/sqlbulksync/build/1.0.2.19/artifacts

Will close this issue as soon as it's released.

**Comment by mohamedmostafa20** [comment]
thanks, it is working fine with me "function deleted".

On Wed, Mar 2, 2016 at 11:52 AM, Mattias Karlsson notifications@github.com
wrote:

> Hi @mohamedmostafa20 https://github.com/mohamedmostafa20,
> 
> A version that supports delete is now in the works via PR #2
> https://github.com/WCOMAB/SqlBulkSync/pull/2, if you want to test it
> you can download it from the build server via
> https://ci.appveyor.com/project/WCOMAB/sqlbulksync/build/1.0.2.19/artifacts
> 
> Will close this issue as soon as it's released.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WCOMAB/SqlBulkSync/issues/1#issuecomment-191162297.

## 

Regards,
Mohamed Mostafa | System Enginer | HorizonTechs
Cell: +2 01225365772
Email: Mohamed.Mostafa@HorizonTechs.com

Phone: EGY +2 02 20800788
Cairo: 26 Ali Amin, Mostafa El.Nahas.Nasr City
